on:
  push:
    paths:
      - 'config/**'
    tags:
      - '*'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  release:
    uses: marvinpinto/action-automatic-releases@latest
    if: startsWith(github.ref, 'refs/tags/')
    with:
      repo_token: "${{ secrets.GITHUB_TOKEN }}"
      prerelease: false
      files: |
        firmware.zip
